### ISSUE TITLE
Index out of range scaling a deployment

### ISSUE THREAD

**Issue by jkleckner** [imhotepio/k9salpha#3]
<img src="https://raw.githubusercontent.com/imhotepio/k9salpha/master/assets/k9s_err.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
I see a panic message when I try to scale a deployment:
`Boom! runtime error: index out of range [1] with length 1`

**To Reproduce**
1. Select the `dp` that I want to scale
2. Press the `s` key
3. Immediately panic out back to the shell
4. This same operations works with `k9s` so it must be a regression.

**Expected behavior**
Allow me to enter an integer scale value.

**Versions (please complete the following information):**
 - OS: OSX 10.15.7
 - K9s: v1.0.0-rc.1
 - K8s: v1.17.15-gke.800

**Additional context**

```
[90m8:44AM[0m [1m[31mERR[0m[0m Boom! runtime error: index out of range [1] with length 1
[90m8:44AM[0m [1m[31mERR[0m[0m goroutine 1 [running]:
runtime/debug.Stack(0x4706cc0, 0x3250d03, 0x0)
	runtime/debug/stack.go:24 +0x9f
github.com/imhotepio/k9s/cmd.run.func1()
	github.com/imhotepio/k9s/cmd/root.go:57 +0x125
panic(0x30bf6e0, 0xc002310438)
	runtime/panic.go:965 +0x1b9
github.com/imhotepio/tview.(*Application).Run.func1(0xc00075e2a0)
	github.com/imhotepio/tview@v0.0.0-00010101000000-000000000000/application.go:243 +0x87
panic(0x30bf6e0, 0xc002310438)
	runtime/panic.go:965 +0x1b9
github.com/imhotepio/k9s/internal/view.(*ScaleExtender).makeScaleForm(0xc0019c21d0, 0xc0019201f0, 0xf, 0xc0023d8ec0, 0x1c, 0x0, 0x0, 0xc0005610d0)
	github.com/imhotepio/k9s/internal/view/scale_extender.go:75 +0x6c5
github.com/imhotepio/k9s/internal/view.(*ScaleExtender).showScaleDialog(0xc0019c21d0, 0xc0019201f0, 0xf, 0xc0023d8ec0, 0x1c, 0x0, 0x0)
	github.com/imhotepio/k9s/internal/view/scale_extender.go:54 +0x6a
github.com/imhotepio/k9s/internal/view.(*ScaleExtender).scaleCmd(0xc0019c21d0, 0xc001b86a00, 0x0)
	github.com/imhotepio/k9s/internal/view/scale_extender.go:48 +0x193
github.com/imhotepio/k9s/internal/view.(*Table).keyboard(0xc000fa4c00, 0xc001b86a00, 0xc0019c2200)
	github.com/imhotepio/k9s/internal/view/table.go:68 +0x111
github.com/imhotepio/tview.(*Box).WrapInputHandler.func1(0xc001b86a00, 0xc002d9b560)
	github.com/imhotepio/tview@v0.0.0-00010101000000-000000000000/box.go:191 +0x7a
github.com/imhotepio/tview.(*Pages).InputHandler.func1(0xc001b86a00, 0xc002d9b560)
	github.com/imhotepio/tview@v0.0.0-00010101000000-000000000000/pages.go:332 +0xb3
github.com/imhotepio/tview.(*Box).WrapInputHandler.func1(0xc001b86a00, 0xc002d9b560)
	github.com/imhotepio/tview@v0.0.0-00010101000000-000000000000/box.go:194 +0x62
github.com/imhotepio/tview.(*Flex).InputHandler.func1(0xc001b86a00, 0xc002d9b560)
	github.com/imhotepio/tview@v0.0.0-00010101000000-000000000000/flex.go:261 +0xae
github.com/imhotepio/tview.(*Box).WrapInputHandler.func1(0xc001b86a00, 0xc002d9b560)
	github.com/imhotepio/tview@v0.0.0-00010101000000-000000000000/box.go:194 +0x62
github.com/imhotepio/tview.(*Pages).InputHandler.func1(0xc001b86a00, 0xc002d9b560)
	github.com/imhotepio/tview@v0.0.0-00010101000000-000000000000/pages.go:332 +0xb3
github.com/imhotepio/tview.(*Box).WrapInputHandler.func1(0xc001b86a00, 0xc002d9b560)
	github.com/imhotepio/tview@v0.0.0-00010101000000-000000000000/box.go:194 +0x62
github.com/imhotepio/tview.(*Application).Run(0xc00075e2a0, 0x0, 0x0)
	github.com/imhotepio/tview@v0.0.0-00010101000000-000000000000/application.go:334 +0x6e2
github.com/imhotepio/k9s/internal/view.(*App).Run(0xc000063980, 0xc00072bc50, 0x2)
	github.com/imhotepio/k9s/internal/view/app.go:470 +0xa5
github.com/imhotepio/k9s/cmd.run(0x46e0120, 0x4742950, 0x0, 0x0)
	github.com/imhotepio/k9s/cmd/root.go:93 +0x305
github.com/spf13/cobra.(*Command).execute(0x46e0120, 0xc000196020, 0x0, 0x0, 0x46e0120, 0xc000196020)
	github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x46e0120, 0x0, 0x0, 0x0)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/imhotepio/k9s/cmd.Execute()
	github.com/imhotepio/k9s/cmd/root.go:48 +0x2d
main.main()
	github.com/imhotepio/k9s/main.go:54 +0x218
```

**Comment by jkleckner** [comment]
It doesn't happen with all deployments.
